/* The tool catalog — extracted verbatim from the shipped landing page so
   names, tags and categories stay the single source of truth. */
function svg(inner: string): string {
  return "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='1.8' stroke-linecap='round' stroke-linejoin='round' aria-hidden='true'>" + inner + "</svg>";
}

export const IC: Record<string, string> = {
    chat: svg("<path d='M4 5h16v11H9l-5 4z'/><path d='M8 9h8M8 12.5h5'/>"),
    receipt: svg("<path d='M6 3h12v18l-2-1.6L14 21l-2-1.6L10 21l-2-1.6L6 21z'/><path d='M9 8h6M9 11.5h6M9 15h4'/>"),
    pen: svg("<path d='M4 20c4 .8 6-.6 5-2.4-.8-1.5-3-1-2.6.8.5 2.2 4 2 6.6-.4'/><path d='m13 15 7-7-2.5-2.5-7 7L10 16z'/>"),
    truck: svg("<path d='M2 6h11v10H2z'/><path d='M13 10h4l3 3v3h-7'/><circle cx='6.5' cy='18' r='1.8'/><circle cx='16.5' cy='18' r='1.8'/>"),
    box: svg("<path d='M3 8 12 3l9 5v8l-9 5-9-5z'/><path d='m3 8 9 5 9-5M12 13v8'/><path d='m8.5 15.5 2 1.6 3.5-3.6'/>"),
    folder: svg("<path d='M3 6h6l2 2h10v11H3z'/><path d='M8 15v-2M12 15v-4M16 15v-6'/>"),
    list: svg("<path d='m4 6 1.5 1.5L8 5'/><path d='m4 12 1.5 1.5L8 11'/><path d='m4 18 1.5 1.5L8 17'/><path d='M11 6.5h9M11 12.5h9M11 18.5h9'/>"),
    building: svg("<path d='M4 21V4h10v17'/><path d='M14 9h6v12'/><path d='M7 8h1.5M7 12h1.5M7 16h1.5M17 13h.5M17 17h.5'/><path d='M2 21h20'/>"),
    audio: svg("<path d='M4 14v-2a8 8 0 0 1 16 0v2'/><path d='M4 14h3v6H4zM17 14h3v6h-3z'/>"),
    mic: svg("<rect x='9' y='3' width='6' height='11' rx='3'/><path d='M5 11a7 7 0 0 0 14 0'/><path d='M12 18v3M9 21h6'/>"),
    cast: svg("<circle cx='12' cy='11' r='2'/><path d='M8.5 14.5a5 5 0 0 1 0-7M15.5 7.5a5 5 0 0 1 0 7'/><path d='M5.6 17.4a9 9 0 0 1 0-12.8M18.4 4.6a9 9 0 0 1 0 12.8'/><path d='m10.5 21 1.5-4 1.5 4'/>"),
    gauge: svg("<path d='M4 19a9 9 0 1 1 16 0'/><path d='m12 15 4.5-5.5'/><circle cx='12' cy='15' r='1.6'/>"),
    exchange: svg("<path d='M4 8h13l-3-3M20 16H7l3 3'/><path d='M4 8v0M20 16v0'/>"),
    calc: svg("<rect x='5' y='3' width='14' height='18' rx='2'/><path d='M8.5 7h7'/><path d='M8.5 12h.5M12 12h.5M15.5 12h.5M8.5 15.5h.5M12 15.5h.5M15.5 15.5h.5M8.5 19h.5M12 19h.5M15.5 19h.5' stroke-width='2.2'/>"),
    book: svg("<path d='M4 4h7v16H6a2 2 0 0 1-2-2z'/><path d='M20 4h-7v16h5a2 2 0 0 0 2-2z'/><path d='M7 8h1.5M15.5 8H17M15.5 11H17'/>"),
    calendar: svg("<rect x='3' y='5' width='18' height='16' rx='2'/><path d='M3 9.5h18M8 3v4M16 3v4'/><path d='M7.5 14h2M11 14h2M14.5 14h2M7.5 17.5h2M11 17.5h2'/>"),
    down: svg("<path d='m3 7 6 6 4-4 8 8'/><path d='M21 12v5h-5'/>"),
    house: svg("<path d='m3 11 9-7 9 7'/><path d='M5 10v10h14V10'/><path d='M10 20v-6h4v6'/>"),
    percent: svg("<path d='m3 11 9-7 9 7'/><path d='M5 10v10h14V10'/><path d='m9.5 17.5 5-5'/><circle cx='9.8' cy='13' r='1'/><circle cx='14.2' cy='17' r='1'/>"),
    scales: svg("<path d='M12 4v16M5 7l7-3 7 3'/><path d='m5 7-2.5 6a3 3 0 0 0 5 0zM19 7l-2.5 6a3 3 0 0 0 5 0z'/><path d='M8 20h8'/>"),
    growth: svg("<path d='m3 12 9-8 9 8'/><path d='M5 11v9h14v-9'/><path d='m8 17 2.5-2.5 1.8 1.5L16 12.5'/><path d='M16 15v-2.5h-2.5'/>"),
    cap: svg("<path d='m2 9 10-5 10 5-10 5z'/><path d='M6 11.5V16c0 1.5 2.7 3 6 3s6-1.5 6-3v-4.5'/><path d='M22 9v5'/>"),
    cash: svg("<rect x='3' y='7' width='18' height='11' rx='2'/><circle cx='12' cy='12.5' r='2.6'/><path d='M12 2.5v2.5M9.5 4l2.5 1 2.5-1' /><path d='M6.5 10.5v4M17.5 10.5v4'/>"),
    compass: svg("<circle cx='12' cy='12' r='9'/><path d='m15.5 8.5-2 5-5 2 2-5z'/><circle cx='12' cy='12' r='.8'/>"),
    dj: svg("<circle cx='12' cy='12' r='9'/><circle cx='12' cy='12' r='3.4'/><circle cx='12' cy='12' r='.9'/><path d='M19.5 5.5 15 10'/>"),
    scissors: svg("<circle cx='6' cy='6' r='2.5'/><circle cx='6' cy='18' r='2.5'/><path d='M8.2 7.6 20 19M8.2 16.4 20 5'/>"),
    tattoo: svg("<path d='m14 3 7 7-2.5 2.5-7-7z'/><path d='m11.5 5.5-7 11L3 21l4.5-1.5 11-7'/><path d='m12 10 2 2'/>"),
    roller: svg("<rect x='4' y='4' width='13' height='5' rx='1.5'/><path d='M17 6.5h3v4.5h-8v3'/><rect x='10.5' y='14' width='3' height='7' rx='1'/>"),
    wrench: svg("<path d='M14.5 6.5a4.5 4.5 0 0 0-6 6L3 18l3 3 5.5-5.5a4.5 4.5 0 0 0 6-6L14 13l-3-3z'/>"),
    leaf: svg("<path d='M5 20C5 9 13 4 21 4c0 8-5 15-16 15'/><path d='M5 20c3-6 7-9 12-11'/>"),
    ledger: svg("<path d='M5 3h13a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H5z'/><path d='M5 3v18M8.5 8h7M8.5 12h7M8.5 16h4'/>"),
    swap: svg("<path d='M7 3v13M7 3 4 6M7 3l3 3'/><path d='M17 21V8M17 21l-3-3M17 21l3-3'/>"),
    shrink: svg("<path d='M9 3v6H3M15 3v6h6M9 21v-6H3M15 21v-6h6'/>"),
    qrpay: svg("<rect x='3' y='3' width='7' height='7' rx='1.5'/><rect x='14' y='3' width='7' height='7' rx='1.5'/><rect x='3' y='14' width='7' height='7' rx='1.5'/><path d='M14 14h3v3h-3zM20 14h1M14 20h1M18 18h3v3h-3z'/>")
  };

export type Tool = {
  href: string; cat: string; ic: string; name: string; desc: string; tags: string;
  core?: number; paid?: boolean;
};

export const TOOLS: Tool[] = [
    { href: "apps/agree.html", cat: "paperwork", ic: "chat", name: "WhatsApp Deal Summary", core: 2,
      desc: "Paste a WhatsApp chat — get a clear deal summary, agreement, quote or payment request.",
      tags: "whatsapp deal agreement contract quote payment customer deposit balance terms chat parse kasi" },
    { href: "apps/receipts.html", cat: "paperwork", ic: "receipt", name: "Receipt & Invoice Maker", core: 3,
      desc: "Professional receipts and invoices with your logo, ready to send as PDF.",
      tags: "receipt invoice billing logo client total pdf sale paid proof of payment" },
    { href: "apps/sign.html", cat: "paperwork", ic: "pen", name: "PDF Signing Link", core: 4,
      desc: "Send a link or QR code; your client signs the PDF once and the signature is destroyed.",
      tags: "sign signature pdf link qr code contract once client esign document" },
    { href: "apps/delivery.html", cat: "management", ic: "truck", name: "Delivery Proof",
      desc: "The customer signs on your phone; you keep the DELIVERED certificate.",
      tags: "delivery proof driver transport furniture food materials stock sign received pod" },
    { href: "apps/stock.html", cat: "management", ic: "box", name: "Stock Delivery Check",
      desc: "Count what arrived against what you ordered — photo, note and supplier dispute.",
      tags: "stock count supplier missing crates dispute wholesale order shop spaza inventory" },
    { href: "apps/evidence.html", cat: "paperwork", ic: "folder", name: "Business Evidence Pack", core: 5,
      desc: "Sales, expenses, customers and stock in one honest pack a bank can read.",
      tags: "bank funding evidence proof income statement profit loan application informal records" },
    { href: "apps/checklist.html", cat: "paperwork", ic: "list", name: "Paperwork Checklist",
      desc: "Say who you want to supply — get the paperwork list, and create what's missing.",
      tags: "checklist supply school government tender corporate documents requirements csd bbbee" },
    { href: "apps/company.html", cat: "paperwork", ic: "building", name: "Company Registration Helper",
      desc: "Everything CIPC's BizPortal asks, collected first — registration in minutes.",
      tags: "company register cipc bizportal pty business directors tax number startup" },
    { href: "apps/career.html", cat: "education", ic: "compass", name: "What Do You Have? (Career Paths)",
      desc: "Tell Makhie what's in your hands — get real career options with difficulty, study time and the path.",
      tags: "career job work options matric grade learnership trade tvet study course it support software office data electrician plumber welder solar driver care food path guidance youth" },
    { href: "apps/study-audio.html", cat: "education", ic: "audio", name: "PDF to Audio & Summary",
      desc: "Drop in a PDF, a screenshot, or paste text — get a summary and audio for your phone.",
      tags: "pdf audio summary study listen voice amr notes exam textbook read aloud screenshot ocr paste text" },
    { href: "apps/pitch.html", cat: "education", ic: "mic", name: "Pitch Script Builder",
      desc: "Five honest answers become one tight pitch, practised against the 20-second clock.",
      tags: "pitch elevator script practice investor idea presentation 20 seconds" },
    { href: "apps/stage.html", cat: "education", ic: "cast", name: "Investor Pitch Board",
      desc: "Post your idea and a 20-second voice pitch; investors read, listen and respond.",
      tags: "investor pitch stage funding finance resources idea board voice public network" },
    { href: "apps/dashboard.html", cat: "management", ic: "gauge", name: "Business Dashboard",
      desc: "Your money on paper, documents, deliveries and shortages — charted over time.",
      tags: "dashboard performance charts revenue stats history records overview" },
    { href: "apps/bookings.html?type=salon", cat: "management", ic: "scissors", name: "Salon & Barber Bookings",
      desc: "Your own booking page: clients pick the day and hour, at the salon or house call — you confirm personally.",
      tags: "salon barber bookings hair fade braids appointment calendar house call beauty nails client schedule" },
    { href: "apps/bookings.html?type=tattoo", cat: "management", ic: "tattoo", name: "Tattoo Bookings",
      desc: "Consults, sessions and touch-ups on your calendar — at the studio or house call.",
      tags: "tattoo artist ink bookings appointment studio session consult cover up calendar" },
    { href: "apps/bookings.html?type=carwash", cat: "management", ic: "truck", name: "Carwash Bookings",
      desc: "Wash & Go to full valet — clients pick the day and hour, at the wash bay or at their place.",
      tags: "carwash car wash valet polish wax vacuum engine mobile detailing bookings appointment calendar bakkie" },
    { href: "apps/bookings.html?type=painter", cat: "management", ic: "roller", name: "House Painter Bookings",
      desc: "Quote visits and job days booked onto your calendar, straight from a link or QR code.",
      tags: "painter painting bookings quote visit interior exterior roof waterproofing calendar" },
    { href: "apps/bookings.html?type=handyman", cat: "management", ic: "wrench", name: "Handyman Bookings",
      desc: "Piece jobs, repairs and quote visits — booked by the hour on your calendar.",
      tags: "handyman general worker piece job repairs bookings fix calendar quote visit maintenance" },
    { href: "apps/bookings.html?type=landscape", cat: "management", ic: "leaf", name: "Landscaping Bookings",
      desc: "Garden cleanups, lawn care and quote visits booked onto your calendar.",
      tags: "landscaping garden lawn tree felling paving irrigation bookings calendar yard" },
    { href: "apps/dj.html", cat: "management", ic: "dj", name: "DJ Quotes & Bookings",
      desc: "Quotes with the full brief, invoices, and deposit + final-payment tracking per gig.",
      tags: "dj gig booking quote brief invoice deposit balance event music wedding party club set entertainer performer" },
    { href: "apps/getpaid.html", cat: "finance", ic: "qrpay", name: "Get Paid in Crypto",
      desc: "A temporary payment request: enter rands, show the QR, receive USDC. Expires on its own.",
      tags: "get paid crypto usdc payment request qr code receive money stablecoin temporary session" },
    { href: "apps/cashbook.html", cat: "finance", ic: "cash", name: "Money In & Money Out", core: 1,
      desc: "A five-second cashbook — and a clean monthly statement with your logo at month end.",
      tags: "money in out cashbook cash flow income expenses record statement month end bookkeeping track spending sales" },
    { href: "apps/accounting.html", cat: "finance", ic: "ledger", name: "Simple Accounting", core: 1,
      desc: "Categorised income and expenses, a monthly profit line, and a management-accounts PDF.",
      tags: "accounting bookkeeping ledger income statement profit loss categories vat expenses management accounts pnl" },
    { href: "apps/convert.html", cat: "paperwork", ic: "swap", name: "Document Converter",
      desc: "Images to PDF, PDF pages to images, and picture formats swapped — on your device.",
      tags: "convert converter document pdf image jpg png webp pages merge photos scan" },
    { href: "apps/compress.html", cat: "paperwork", ic: "shrink", name: "Document Compressor",
      desc: "Shrink photos and PDFs until they fit in an email or WhatsApp — quality you control.",
      tags: "compress compressor shrink smaller file size pdf image photo email attachment reduce mb" },
    { href: "apps/ratecheck.html", cat: "finance", ic: "exchange", name: "Currency & Crypto Converter",
      desc: "Any currency into rand at live rates, plus real-time crypto prices.",
      tags: "currency convert exchange rate dollar usd euro pound naira zar rand forex bitcoin btc ethereum crypto coin live" },
    { href: "apps/loans.html", cat: "finance", ic: "calc", name: "Loans & Bonds",
      desc: "Loan repayments, the true monthly cost of a home loan, and rental yield — one calculator.",
      tags: "loan repayment calculator interest monthly instalment credit borrow cost bond home house mortgage property deposit bank rental yield rent income gross net landlord investment returns" },
    { href: "apps/loantrack.html", cat: "finance", ic: "book", name: "Money Owed Tracker",
      desc: "Who owes you, how much, since when — with WhatsApp reminders one tap away.",
      tags: "owe owed track lend borrow debt book credit customers remind whatsapp mashonisa ledger" },
    { href: "apps/payplan.html", cat: "finance", ic: "calendar", name: "Repayment Schedule",
      desc: "Month by month: interest, balance, and the month the loan hits zero.",
      tags: "repayment schedule amortisation plan months interest balance payoff table pdf" },
    { href: "apps/debtfree.html", cat: "finance", ic: "down", name: "Debt Payoff Planner",
      desc: "List your debts and extra payment — see how fast you can be free, two ways.",
      tags: "debt free payoff snowball avalanche interest saved credit cards store accounts plan" },
    { href: "apps/rentvsbuy.html", cat: "finance", ic: "scales", name: "Rent vs Buy Comparison",
      desc: "The true cost of renting vs owning over the years you'd actually stay.",
      tags: "rent buy compare home house property decision equity bond stay" },
    { href: "apps/propertyroi.html", cat: "finance", ic: "growth", name: "Property Investment Return",
      desc: "Cashflow, cash-on-cash return, and the five-year view of a rental property.",
      tags: "property investment return roi cashflow rental equity growth five year" },
    { href: "https://edu.nerdimee.io/re5", cat: "education", ic: "cap", name: "RE5 Exam Prep", paid: true,
      desc: "Exam preparation for the RE5 regulatory exam.",
      tags: "re5 exam prep study regulatory fais financial services mock drill readiness" }
  ];
